#!/bin/bash

DISK=$1.qcow2
MEMORY=2048
CORES=2

echo "##### Starting VM #####"

qemu-system-x86_64 -hda $DISK -smp $CORES -m $MEMORY -net user,hostfwd=tcp::10022-:22 -net nic -display none -daemonize -enable-kvm -cpu host,-svm

sleep 20

PID=$(pgrep qemu-system)

echo "SSH into the VM with: ssh sandbox@localhost -p 10022"
echo "PID of VM: $PID"
